---
- name: Deploy App
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Wait for server to boot
      ansible.builtin.wait_for_connection:
        timeout: 120

    - name: Gather facts
      ansible.builtin.setup:

    - name: Checkout repository
      ansible.builtin.git:
        repo: 'https://github.com/krixapolinario/getting-started-app.git'
        dest: /srv/checkout

    - name: Build image
      community.docker.docker_image:
        name: todoapp
        tag: v1
        build:
          path: './getting-started-app/'
          pull: false
        source: local

    - name: Deploy app
      community.docker.docker_stack:
        state: present
        name: todoapp
        compose:
          - ./getting-started-app/docker-compose.yml
